### ISSUE TITLE
Status of this port

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/uc_price_per_role#2]
@bugfolder Is this module relatively stable? Are you willing to make a release or does it need further testing first?

**Comment by bugfolder** [comment]
It's working in my testing. It has a release (3 actually), which I'd left at "alpha" until I got some further indication that others had tried it out (currently there's only one (my) install). If you (or anyone else) would try it out and verify that it works in your situation, I'll drop the alpha and make a standard release.

**Comment by samgreco** [comment]
I did some initial testing on this and it worked well.  But the project to move from Drupal 7 stalled and they haven't moved forward.  One thing I needed that I wasn't able to do (not this module's fault really) was to be able to expose the PPR fields in Feeds so that we could import price sheets.

But in my tests, this worked perfectly.

**Comment by laryn** [comment]
Great, thanks! I have a project I'll likely use this on so I'll try to test in the next week or two.

**Comment by laryn** [comment]
In early testing this seems to be working well.

@samgreco You should be able to follow the model from `uc_feeds` to implement PPR fields as targets in feeds (or hire someone to do that) using `hook_feeds_processor_targets_alter()`. See: https://github.com/backdrop-contrib/uc_feeds/blob/1.x-1.x/uc_feeds.module

**Comment by laryn** [comment]
I broke the feeds conversation out here: https://github.com/backdrop-contrib/uc_price_per_role/issues/3

**Comment by samgreco** [comment]
It may be a while before I can get back to this.  But I will as soon as I can and let you know

Thanks!

**Comment by bugfolder** [comment]
I'll have a PR for https://github.com/backdrop-contrib/uc_price_per_role/issues/5 pretty soon, and once that's merged, I'll do a regular release. But I'll hold off on incorporating https://github.com/backdrop-contrib/uc_price_per_role/issues/3 until I hear some testing results, so please test it when you can.

**Comment by bugfolder** [comment]
PR for #5 is merged, 1.0.0 is now released.
