### ISSUE TITLE
Feeds integration

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/uc_price_per_role#3]
From @samgreco in another thread:

> I did some initial testing on this and it worked well. But the project to move from Drupal 7 stalled and they haven't moved forward. One thing I needed that I wasn't able to do (not this module's fault really) was to be able to expose the PPR fields in Feeds so that we could import price sheets.

I have a relatively small import but decided I'd try to set this up at a basic level rather than just adjust member prices manually after the import as I had been initially planning. I'll submit a basic PR for testing. (I have not fleshed it out for attributes, etc. it's just a very basic integration.)

**Comment by bugfolder** [comment]
@Laryn, are you comfortable with this PR for merging?

**Comment by samgreco** [comment]
I have finally gotten back to this project as the site owner finally wants to move forward.  Just test this and it works perfectly.  Using it to import products as well as, later, to update pricing.

Thanks for this.
